# Generated by Django 5.2.3 on 2025-06-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
